#!/usr/bin/env node
/**
 * Generate Tailwind CSS and embed it into a TypeScript module.
 * Run before esbuild so the CSS is available as a string constant.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");
const cssFile = join(root, "src/templates/tailwind.css");
const tsFile = join(root, "src/templates/tailwind-generated.ts");

// Run Tailwind CLI — resolve from hoisted node_modules (workspaces) or local
import { createRequire } from "node:module";
const require = createRequire(join(root, "package.json"));
const tailwindBin = join(dirname(require.resolve("tailwindcss/package.json")), "lib/cli.js");
execFileSync(
  process.execPath,
  [
    tailwindBin,
    "-c", join(root, "tailwind.config.cjs"),
    "-i", join(root, "src/templates/input.css"),
    "-o", cssFile,
    "--minify",
  ],
  { stdio: ["ignore", "ignore", "inherit"] },
);

// Read the generated CSS
const css = readFileSync(cssFile, "utf-8");

// Write it as a TypeScript string export using JSON.stringify for safe escaping
const tsContent = `// AUTO-GENERATED by scripts/build-css.mjs — do not edit manually.\nexport const tailwindCSS: string = ${JSON.stringify(css)};\n`;
writeFileSync(tsFile, tsContent);

const bytes = Buffer.byteLength(css, "utf-8");
console.error(`Tailwind CSS: ${bytes} bytes -> ${tsFile}`);
